CREATE TABLE [dbo].[Information] (
    [PLAYER_ID]        INT          IDENTITY (1, 1) NOT NULL,
    [Player_Name]      VARCHAR (50) NOT NULL,
    [server]           VARCHAR (50) NOT NULL,
    [Race]             VARCHAR (50) NOT NULL,
    [Selected Hat]     VARCHAR (50) NOT NULL,
    [Color Of Hat]     VARCHAR (50) NOT NULL,
    [Selected Shirt]   VARCHAR (50) NOT NULL,
    [Color Of Shirt]   VARCHAR (50) NOT NULL,
    [Selected Pants]   VARCHAR (50) NOT NULL,
    [Color Of Pants]   VARCHAR (50) NOT NULL,
    [Selected Boots]   VARCHAR (50) NOT NULL,
    [Color Of Boots]   VARCHAR (50) NOT NULL,
    [Eye Color]        VARCHAR (50) NOT NULL,
    [Skin Color]       VARCHAR (50) NOT NULL,
    [Height]           VARCHAR (50) NOT NULL,
    [Weight]           VARCHAR (50) NOT NULL,
    [Hard Mode]        BIT          NOT NULL,
    [Primary Class]    VARCHAR (50) NOT NULL,
    [Secondary Class]  VARCHAR (50) NOT NULL,
    [Selected Element] VARCHAR (50) NOT NULL,
    [Pet]              VARCHAR (50) NOT NULL,
    [Pet Element]      VARCHAR (50) NOT NULL,
    [Health]           INT          NOT NULL,
    [Strength]         INT          NOT NULL,
    [Agility]          INT          NOT NULL,
    [GENDER]           VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([PLAYER_ID] ASC)
);

